POST http://localhost:8080/api/0.1/signup
Content-Type: application/json

{
  "email": "dinar@gmail.com",
  "name": "dinar",
  "surname": "shagaliev",
  "password": "dinar123"
}
###

POST http://localhost:8080/api/0.1/login
Content-Type: application/json

{
  "email": "dinar@gmail.com",
  "password": "dinar123",
  "deviceFingerprint": "idea"
}

###

GET http://localhost:8080/api/0.1/profile
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZSI6IlVTRVIiLCJzdGF0ZSI6IkFDVElWRSIsImlkIjoxLCJleHAiOjE2MTg4MTU4NTYsImlhdCI6MTYxODgxNDA1NiwiZW1haWwiOiJkaW5hckBnbWFpbC5jb20ifQ.7qVtTARYAaHNDJ5nvYbiSTL5BZUtZavUucao1NUArDw

###

GET http://localhost:8080/api/0.1/refresh_tokens
Content-Type: application/json

{
  "accessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZSI6IlVTRVIiLCJzdGF0ZSI6IkFDVElWRSIsImlkIjoxLCJleHAiOjE2MTg4MTU4NTYsImlhdCI6MTYxODgxNDA1NiwiZW1haWwiOiJkaW5hckBnbWFpbC5jb20ifQ.7qVtTARYAaHNDJ5nvYbiSTL5BZUtZavUucao1NUArDw",
  "refreshToken": "24790500-fec7-4fb6-ab72-57b717087e41",
  "deviceFingerprint": "idea"
}

###


#  "accessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZSI6IlVTRVIiLCJzdGF0ZSI6IkFDVElWRSIsImlkIjoxLCJleHAiOjE2MTg3Nzc1MzMsImlhdCI6MTYxODc3NTczMywiZW1haWwiOiJkaW5hckBnbWFpbC5jb20ifQ.N7NVYLiTB4M3pduqBXAUz0uhlOLQuZeNv639Od13bPU",
#  "refreshToken": "daa5f205-8268-4b3b-b3f2-92d0f4f5a4ed"
